@startuml
title Pod啟動過程

skinparam handwritten true
skinparam ParticipantBackgroundColor #EEEBDC
skinparam ParticipantBorderColor #FFFFFF

actor User

User -> APIServer : 創建Pod
activate APIServer
APIServer -> Etcd : 存儲PodSpec
deactivate APIServer

Scheduler --> APIServer : 監聽Pod，調度Node

APIServer -> Etcd : 更新Node綁定

Kubelet --> APIServer : 監聽Pod
Kubelet -> docker : 啟動Docker Sandbox
docker -> CNI : 配置sandbox網絡
CNI --> docker
docker --> Kubelet
Kubelet --> APIServer : 更新Pod狀態
APIServer -> Etcd : 存儲Pod狀態

@enduml