---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: admin-user
rules:
  - apiGroups:
      - "*"
    resources:
      - '*'
    verbs:
      - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin-user
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: default

