---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  secret-data: YWRtaW4=

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: example-config
  namespace: default
data:
  configmap-data: configmap-value-1

---
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - command:
    - sh
    - -c
    - cat /all/podname && cat /all/secret-data && cat /all/configmap-data
    image: gcr.io/google_containers/busybox:1.24
    name: projected-all-volume-test
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /all
      name: podinfo
  dnsPolicy: Default
  restartPolicy: Never
  schedulerName: default-scheduler
  terminationGracePeriodSeconds: 30
  volumes:
  - name: podinfo
    projected:
      defaultMode: 420
      sources:
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
            path: podname
      - secret:
          name: mysecret
      - configMap:
          name: example-config
