apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    command:
    - sh
    - -c
    - touch test.go && [ -f test.go ] && echo 'Found'
    securityContext:
      readOnlyRootFilesystem: true
    ports:
    - containerPort: 80

