apiVersion: v1
kind: Pod
metadata:
  name: http
  labels:
    app: http
spec:
  containers:
  - name: http
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "2000m"
