@startuml
title Pod Start Procedure

skinparam handwritten true
skinparam ParticipantBackgroundColor #EEEBDC
skinparam ParticipantBorderColor #FF8844

actor User

User -> APIServer : Create Pod
activate APIServer
APIServer -> Etcd : Store PodSpec
deactivate APIServer

Scheduler --> APIServer : Watch Pod and scheduler to a Node
APIServer -> Etcd : Update pod's Node

Kubelet --> APIServer : Watch Pods by syncLoop
Kubelet -> KubeGenericRuntimeManager : SyncPod
KubeGenericRuntimeManager -> dockershim : createPodSandbox
dockershim -> docker: RunPodSandbox
dockershim -> CNI: Setup sandbox network
CNI --> dockershim
dockershim --> KubeGenericRuntimeManager

KubeGenericRuntimeManager -> dockershim: pullImage and startContainer
dockershim -> docker: pullImage and startContainer
docker --> dockershim
dockershim --> KubeGenericRuntimeManager

Kubelet --> APIServer : Update Pod to Running
APIServer -> Etcd : Store Pod status

@enduml
