@startuml

skinparam handwritten true

actor 老王 as Wang
participant 奸商 as js
participant 支付寶 as alipay
participant 無良借款公司 as debit
participant 土 as dust

Wang -> js: 老闆 來個iPhone2017
note left: 手機摔了\n買個新的吧

js -> Wang: 一口價 10000元
note right: 生意上門了\n看起來是個肥豬

alt 爺有錢
    Wang -> alipay: 付款 10000 元
    alipay -> js: 打款 10000 元
    js -> Wang: 手機是你的了
else 手頭緊
    Wang -> debit: 借款 10000 元
    debit -> Wang: 月息 10% 的借款
    Wang -> js: 老闆 給你錢
    js -> Wang: 手機是你的了
    loop 持續半年
        Wang -> dust: 吃土
    end
end

@enduml
